### ISSUE TITLE
last file opened misses a tab and is invisible in file tree

### ISSUE THREAD

**Issue by Vluuks** [cs50/labs#14] opened 2019-02-05 13:28 UTC
If there are multiple files present in the editor, the last added file (that is open upon opening the lab) does not have a tab associated with it. It exists in the editor but it cannot be reopened once the user switches tabs, because it does not show in the file tree on the left. 

For example, in the following lab, the file `ConstantTest` exists, it can be compiled and run, but if you switch tabs to another file after opening the lab, it cannot be reopened or edited again, and is not visible in the left directory overview either:

https://lab.cs50.io/Vluuks/AndroidPractice/labified/Week2/Lab/

Order of opening in the yml seems to influence which file is "hidden" but I could not reliably reproduce it. But it seems to be the file/tab that is added last.

**Comment by dmalan** [comment] 2019-02-05 15:45
Wow, that's an odd one. I was able to reproduce as well. Just dropped the team a note to inquire!

**Comment by dmalan** [comment] 2019-02-05 16:30
Okay, turns out `ConstantTest` is matching a regex that's looking for `nttest`, which is an internal testing symbol. Should be fixed shortly, sorry for the trouble!

**Comment by dmalan** [comment] 2019-02-05 19:39
This should now be fixed, thanks for reporting!

**Closed as completed by dmalan** 2019-02-05 19:39 UTC
Labels: bug

**Comment by Vluuks** [comment] 2019-02-05 19:55
Oh, that explains why the other lab with StudentTest was also in trouble!! =) Interesting, thanks for the swift response. 👍
